instances:
  radarr:
    radarr_uhd:
      url: # http://127.0.0.1:7878
      api: # API KEY
    radarr_hd:
      url:
      api:
  sonarr:
    sonarr_uhd:
      url:
      api:
    sonarr_hd:
      url:
      api:
    sonarr_anime:
      url:
      api:
  plex:
    plex:
      url: # http://127.0.0.1:32400
      api: # PLEX TOKEN

schedule:
  poster_renamerr: # daily(13:00)
  unmatched_assets: # weekly(sunday@12:00)
  plex_uploaderr:
  # hourly(30)
  # monthly(13@05:00)
  # cron(0 3 * * *)

log_level:
  unmatched_assets: # INFO
  poster_renamerr: # DEBUG
  plex_uploaderr: # INFO

unmatched_assets:
  show_all_unmatched: # False -- show true unmatched assets (unreleased items + items not on disk)

plex_uploaderr:
  reapply_posters: # False -- force upload posters to libraries regardless of whether they were already uploaded

poster_renamerr:
  asset_folders: # False -- must match kometa asset folder configuration
  clean_assets: # False -- clean orphaned asset files in asset directory on each run
  unmatched_assets: # True -- run unmatched assets after every renamer run
  show_all_unmatched: # False -- show true unmatched assets (all series/seasons + shows added in the arrs)
  replace_border: # False -- only remove borders currently implemented
  border_setting:
  # SUPPORTED COLORS:
  # "black", "remove"
  hex_code: #123456 ## HEX CODE
  run_on_single_item: # True -- must have ports exposed and instances must be setup in arr settings and match instances in config
  upload_to_plex: # False -- when true will change poster in plex to posters in asset directory
  match_alt: # False -- match alternate titles for series only
  library_names:
  # must match plex library names
  # - Movies
  # - TV Shows
  source_directories:
  # folders containing posters -- TOP is highest priority
  # -  /posters/folder
  target_directory: # /assets  -- kometa asset folder
  instances:
  # must match instances at top
  # - plex
  # - radarr_uhd
  # - sonarr_hd
