services:
  daps_ui:
    container_name: daps_ui
    # image: monster117/daps-ui:develop
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - APP_MODE=WEB
      - FLASK_ENV=development
      - TZ=America/Vancouver
      - PUID=501
      - PGID=20
    ports:
      - "8888:8000"
    volumes:
      - ../:/code
      # - path to config directory:/config
      # - path to poster folders:/posters
      # - path to kometa asset folder:/assets
  # daps_cli:
  #   container_name: # daps_cli
  #   environment:
      # - APP_MODE=CLI
      # - TZ=America/Vancouver
      # - PUID=1000
      # - PGID=1000
    # ports:
      # - "5000:5000" - Needed if want to use run renamer on new item in arrs
    # volumes:
      # - path to config directory:/config
      # - path to poster folders:/posters
      # - path to kometa asset folder:/assets
